import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarComponent from "@/components/layout/Sidebar/SidebarComponent";
import { SidebarProvider } from "@/components/ui/sidebar";
import NavbarComponent from "@/components/layout/Navbar/NavbarComponent";
import { LanguageProvider } from "@/contexts/useLanguage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider>
          <div className="flex min-h-screen">
            <div className="w-64">
              <SidebarProvider>
                <SidebarComponent />
              </SidebarProvider>
            </div>
            <div className="flex-1">
              <NavbarComponent />
              <div className="p-4">{children}</div>
            </div>
          </div>
        </LanguageProvider>
      </body>
    </html>
  );
}
